### ISSUE TITLE
ImportError: cannot import name 'is_osx' from 'libpcap._platform'

### ISSUE THREAD

**Issue by Ethycs** [karpierz/pcap-ct#10]
```
>>> import pcap
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Keytone\miniconda3\lib\site-packages\pcap\__init__.py", line 8, in <module>
    from ._pcap import *  # noqa
  File "C:\Users\Keytone\miniconda3\lib\site-packages\pcap\_pcap.py", line 37, in <module>
    from . import _pcap_ex
  File "C:\Users\Keytone\miniconda3\lib\site-packages\pcap\_pcap_ex.py", line 13, in <module>
    from libpcap._platform import defined, is_windows, is_osx
ImportError: cannot import name 'is_osx' from 'libpcap._platform' (C:\Users\Keytone\miniconda3\lib\site-packages\libpcap\_platform\__init__.py)
```

**Comment by karpierz** [comment]
Fixed by general update (1.2.3b13 release).
