### ISSUE TITLE
TypeError: 'CArgObject' object is not subscriptable

### ISSUE THREAD

**Issue by gil-obradors** [karpierz/pcap-ct#5]
I have not idea what are [ct.cast()](https://docs.python.org/3/library/ctypes.html#ctypes.cast).. sorry!
code execution
```
import pcap

sniffer = pcap.pcap(name=None, promisc=True, immediate=True, timeout_ms=50)
addr = lambda pkt, offset: '.'.join(str(ord(pkt[i])) for i in range(offset, offset + 4))
for ts, pkt in sniffer:
    print('%d\tSRC %-16s\tDST %-16s' % (ts, addr(pkt, sniffer.dloff + 12),
                                        addr(pkt, sniffer.dloff + 16)))
```
Error
```
runfile('/home/gil/PycharmProjects/netdiscover/main.py', wdir='/home/gil/PycharmProjects/netdiscover')
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/snap/pycharm-professional/230/plugins/python/helpers/pydev/_pydev_bundle/pydev_umd.py", line 197, in runfile
    pydev_imports.execfile(filename, global_vars, local_vars)  # execute the script
  File "/snap/pycharm-professional/230/plugins/python/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/home/gil/PycharmProjects/netdiscover/main.py", line 6, in <module>
    for ts, pkt in sniffer:
  File "/home/gil/PycharmProjects/netdiscover/venv/lib/python3.8/site-packages/pcap/_pcap.py", line 387, in __next__
    n = _pcap_ex.next_ex(self.__pcap, ct.byref(phdr), ct.byref(pkt))
  File "/home/gil/PycharmProjects/netdiscover/venv/lib/python3.8/site-packages/pcap/_pcap_ex.py", line 172, in next_ex
    pkt = ct.cast(_pcap.next(pcap, hdr[0]), ct.POINTER(ct.c_ubyte))
TypeError: 'CArgObject' object is not subscriptable

```
https://github.com/karpierz/pcap-ct/blob/85930944b9d2087dbd0ad9add32b70ca116811b6/src/pcap/_pcap_ex.py#L172

**Comment by 4788665** [comment]
https://github.com/4788665/pcap-ct
src/pcap/_pcap.py，line349/389
n = _pcap_ex.next_ex(self.__pcap, ct.pointer(phdr), ct.pointer(pkt))
